version: '3'
services:
  tftpserver2:
    image: alpine:3.21.0
    container_name: tftpserver2
    command: sh -c "/server/tftp_server /share 3069"
    volumes:
      - ./share:/share/
      - ./tftp_server:/server/tftp_server
    network_mode: host
    restart: always